### ISSUE TITLE
Civi 5.25.0 Error - Call to undefined method CRM_ACL_BAO_Cache::updateEntry() in 	GroupContact.php:159

### ISSUE THREAD

**Issue by encircle** [mattwire/civicrm-groupaclcache#1]
We were evaluating this extension to see if it stopped profiles disapearing on an ad-hoc basis. Didn't sort the issue, but we left the extension enabled on test. Now we've upgraded to 5.25.0 and if a user submits a Profile (standalone form in Edit mode) then the follow stack trace is logged and a cirtical error shown on the frontend. This is when the contact is being added to the group configured on the Profile.

#0 //wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Contact.php(2049): CRM_Contact_BAO_GroupContact::addContactsToGroup(Array, '37')
#1 //wp-content/plugins/civicrm/civicrm/CRM/Profile/Form.php(1281): CRM_Contact_BAO_Contact::createProfileContact(Array, Array, '10887', '37', 42, NULL, true)
#2 //wp-content/plugins/civicrm/civicrm/CRM/Profile/Form/Edit.php(245): CRM_Profile_Form->postProcess()
#3 //wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(484): CRM_Profile_Form_Edit->postProcess()

**Comment by mattwire** [comment]
@encircle This extension was meant for 5.13.4 only and everything has been in CiviCRM core since around 5.19 I think
